BOT_TOKEN = 'YOUR_BOT_TOKEN_HERE'
ADMIN_ID = 'YOUR_ADMIN_ID_HERE'
CHANNEL_ID = '@trysmthhhh'

# API-ключ Gemini (получить на https://aistudio.google.com/)
GEMINI_API_KEY = 'YOUR_GEMINI_API_KEY_HERE'
OPENROUTER_API_KEY = 'YOUR_OPENROUTER_API_KEY_HERE'