"RENAME THIS FILE TO private_cfg.py AND FILL IN THE VALUES"
BOT_TOKEN = 'YOUR_BOT_TOKEN_HERE'
ADMIN_ID = 'YOUR_ADMIN_ID_HERE'
CHANNEL_ID = 'YOUR_CHANNEL_ID_HERE'

GEMINI_API_KEY = 'YOUR_GEMINI_API_KEY_HERE'
OPENROUTER_API_KEY = 'YOUR_OPENROUTER_API_KEY_HERE'